module.exports = [
  { method: 'GET', path: '/health' },

  { method: 'POST', path: '/auth/login' },
  { method: 'POST', path: '/auth/logout' },
  { method: 'GET', path: '/auth/me' },
  { method: 'POST', path: '/auth/change-password' },
  { method: 'GET', path: '/auth/sessions' },
  { method: 'POST', path: '/auth/revoke-sessions' },

  { method: 'GET', path: '/users' },
  { method: 'GET', path: '/users/:id' },
  { method: 'POST', path: '/users' },
  { method: 'PUT', path: '/users/:id' },
  { method: 'DELETE', path: '/users/:id' },

  { method: 'GET', path: '/movies' },
  { method: 'GET', path: '/movies/:id' },
  { method: 'GET', path: '/movies/:id/revisions' },
  { method: 'POST', path: '/movies' },
  { method: 'PUT', path: '/movies/:id' },
  { method: 'POST', path: '/movies/:id/poster' },
  { method: 'POST', path: '/movies/:id/stills' },
  { method: 'POST', path: '/movies/:id/unpublish' },
  { method: 'POST', path: '/movies/:id/republish' },
  { method: 'DELETE', path: '/movies/:id' },

  { method: 'POST', path: '/movie-import/upload' },
  { method: 'GET', path: '/movie-import/:jobId' },
  { method: 'PUT', path: '/movie-import/:jobId/resolve/:recordIndex' },
  { method: 'POST', path: '/movie-import/:jobId/skip/:recordIndex' },
  { method: 'POST', path: '/movie-import/:jobId/execute' },

  { method: 'GET', path: '/content' },
  { method: 'GET', path: '/content/:id' },
  { method: 'GET', path: '/content/:id/reviews' },
  { method: 'POST', path: '/content' },
  { method: 'PUT', path: '/content/:id' },
  { method: 'POST', path: '/content/:id/submit' },
  { method: 'POST', path: '/content/:id/unpublish' },
  { method: 'DELETE', path: '/content/:id' },

  { method: 'POST', path: '/content-review/:id/review' },

  { method: 'GET', path: '/rides' },
  { method: 'GET', path: '/rides/:id' },
  { method: 'POST', path: '/rides' },
  { method: 'POST', path: '/rides/:id/cancel' },
  { method: 'POST', path: '/rides/:id/feedback' },

  { method: 'GET', path: '/dispatch/queue' },
  { method: 'POST', path: '/dispatch/rides/:id/accept' },
  { method: 'POST', path: '/dispatch/rides/:id/transition' },
  { method: 'POST', path: '/dispatch/rides/:id/approve-cancel' },
  { method: 'GET', path: '/dispatch/disputes' },
  { method: 'GET', path: '/dispatch/disputes/:id' },
  { method: 'POST', path: '/dispatch/disputes/:id/assign' },
  { method: 'POST', path: '/dispatch/disputes/:id/resolve' },
  { method: 'GET', path: '/dispatch/carpool/candidates/:id' },
  { method: 'POST', path: '/dispatch/carpool/group' },
  { method: 'GET', path: '/dispatch/carpool/group/:groupId' },

  { method: 'POST', path: '/disputes' },

  { method: 'GET', path: '/search' },
  { method: 'GET', path: '/search/suggest' },

  { method: 'GET', path: '/recommendations/movies' },
  { method: 'GET', path: '/recommendations/content' },

  { method: 'POST', path: '/sensors/ingest' },
  { method: 'POST', path: '/sensors/ingest/batch' },
  { method: 'GET', path: '/sensors/devices' },
  { method: 'GET', path: '/sensors/devices/:id' },
  { method: 'POST', path: '/sensors/devices' },
  { method: 'POST', path: '/sensors/devices/:id/rotate-secret' },
  { method: 'PUT', path: '/sensors/devices/:id' },
  { method: 'GET', path: '/sensors/readings/:deviceId' },

  { method: 'POST', path: '/ledger/entries' },
  { method: 'GET', path: '/ledger/entries' },
  { method: 'GET', path: '/ledger/reconciliation/:date' },
  { method: 'POST', path: '/ledger/reconciliation/:date/close' },

  { method: 'GET', path: '/config' },
  { method: 'GET', path: '/config/:key' },
  { method: 'POST', path: '/config' },
  { method: 'PUT', path: '/config/:key' },
  { method: 'DELETE', path: '/config/:key' },

  { method: 'POST', path: '/extensions/clients' },
  { method: 'GET', path: '/extensions/clients' },
  { method: 'GET', path: '/extensions/movies' },
  { method: 'GET', path: '/extensions/content' },
  { method: 'GET', path: '/extensions/rides' },
];
